Homework2
made-ml-in-prod-2021/pollytur pull request #3
Opened 2021-05-19 18:50 UTC by pollytur

2021-05-24 08:06 UTC, Mikhail-M requested changes
кода первого дз не должно быть здесь

2021-05-27 08:47 UTC, pollytur commented
Поправила

2021-06-13 15:04 UTC, Mikhail-M requested changes
![image](https://user-images.githubusercontent.com/5405304/121812738-bf6e9c00-cc71-11eb-9f96-ec310477bbd8.png)
в реквесте не должно быть этих зачеркиваний

2021-06-14 11:17 UTC, closed without merging

2021-06-14 11:31 UTC, pollytur commented
Из-за сообщения git `The homework2 branch was force-pushed or recreated` залить исправленную версию не вышло. Создам новый PR.